# Generated by Django 3.1.7 on 2021-07-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210702_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
